### ISSUE TITLE
Assign license to repository

### ISSUE THREAD

**Issue by Madekuji** [Ryu1845/delete_otak#1]
Hi there!

Thank you for taking the time to make a bot that tries to solve the big issue of people posting Otakmori's mistranslations and shitsubs in Discord servers. This is a genuine need that people in some servers utilize, including myself. I tested out the code using the repl.it method in a couple of my servers to find it working. However, I've also been asked by my friends if the bot can be used in servers of larger capacity, such as fanservers, as well as implementing features like basic statistics and a wider blacklist for moderation purposes.

I then used some of the code from this repository to create a new project: https://github.com/Madekuji/AntiBadSubs
However, as a beginner coder, I only found out recently that public GitHub repositories that do not have a custom license like GPL don't get automatically attached a standard open-source GitHub license, unlike YouTube with their Standard YouTube License for example, [and that full copyright applies to GitHub code without custom licenses, even if they are public repositories](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license).

I would like to ask if this repository can be assigned an open-source license in order for projects like mine to continue existing and to support other forks or projects based on this repository should they be created by others in the future. I'm also prepared to take down the project I made based on some code from this repository, should you request.

Thank you for your consideration.

**Comment by Ryu1845** [comment]
My code is mostly boilerplate from the getting started page to be quite honest. I don't know if it deserves a license for its 4-5 original lines of code. 
However, adding it requires very little effort so I'll do it now.

**Comment by Ryu1845** [comment]
Done with https://github.com/Ryu1845/delete_otak/commit/27469c0285f80ff47aa59c932e557e99b368e4c8
